#+TITLE:  =org-css=: An =org-mode= compatible style sheet
#+AUTHOR: Diego Vicente Martín
#+EMAIL:  mail@diego.codes

This repository contains my own shot at providing a compatible CSS style sheet
with the HTML output generated by =org-mode= when exporting. It is based on the
magnificent [[https://thomasf.github.io/solarized-css/][Solarized CSS]] project style sheet, and it still uses some of its
definitions for more esoteric =org-mode= artifacts as a fallback.

If you want to use the this style sheet for your own projects, clone this
repository or download the =stylesheet.css= file and simply add this line to
your file prior to exporting it to HTML :

#+BEGIN_SRC org
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="stylesheet.css" />
#+END_SRC

On the other hand, if you prefer not to download the file and just use it
as-is, you can just link to the file in the GitHub repository:

#+BEGIN_SRC org
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://raw.githubusercontent.com/DiegoVicen/org-css/master/stylesheet.css" />
#+END_SRC

-----

This code is licensed under MIT License, which allows for free use,
modification and distribution. Attribution is not needed but appreciated, and
the code is provided without warranty or liability. A copy of the MIT License
is included in the repository.
